version: '3'
services:
  redis:
    image: redis:5.0.3-stretch
    container_name: oogl
    ports:
      - 6379:6379

  postgresql:
    image: postgres:15
    container_name: ogl
    restart: always
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
